[package]
name = "vtracer"
version = "0.6.4"
authors = ["Chris Tsang <chris.2y3@outlook.com>"]
edition = "2021"
description = "A cmd app to convert images into vector graphics."
license = "MIT OR Apache-2.0"
homepage = "http://www.visioncortex.org/vtracer"
repository = "https://github.com/visioncortex/vtracer/"
categories = ["graphics"]
keywords = ["svg", "computer-graphics"]

[dependencies]
clap = "2.33.3"
image = { version = "0.23.10" }
visioncortex = { git = "https://github.com/nikitalita/visioncortex.git", branch = "fix-crash" }
pyo3 = { version = "0.19.0", optional = true }
gifski = "1.34.0"

[build-dependencies]
cbindgen = "0.24.0"

[features]
python-binding = ["pyo3"]

[lib]
name = "vtracer"
# static library
crate-type = ["staticlib"]

[package.metadata.vtracer]
bindings-name = "vtracer"
